import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const userInterfaceSearchEntries = [
  { id: "tray-icon", section: "userInterface", anchor: "tray-icon-settings", labelKey: "settings.userInterface.showTrayIcon.label", fallbackLabel: "Show Tray Icon", keywords: ["tray", "tray icon", "system tray", "notification area", "blink", "blinking", "трей", "иконка в трее", "мигание"] },
  { id: "overlay", section: "userInterface", anchor: "recording-overlay-settings", labelKey: "settingsSearch.items.overlay", fallbackLabel: "Recording overlay", keywords: ["overlay", "finalizing", "recording indicator", "appearance", "оверлей", "финализация"] },
  { id: "overlay-drag-grip", section: "userInterface", anchor: "recording-overlay-drag-grip", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.dragGrip.label", fallbackLabel: "Show Recording Overlay Drag Grip", keywords: ["handle", "drag handle", "grip", "drag", "move overlay", "move the overlay", "move recording overlay", "reposition", "hover", "ручка", "перетаскивание", "переместить оверлей"] },
  { id: "decapitalize-indicator", section: "userInterface", anchor: "recording-overlay-decapitalize-indicator", expandAnchor: "recording-overlay-settings", labelKey: "settingsSearch.items.decapitalizeIndicator", fallbackLabel: "Decapitalize indicator appearance", keywords: ["de", "dec", "decap", "decapitalize", "decapitalization", "lowercase indicator", "capitalization", "case", "декапитализация", "индикатор регистра", "нижний регистр"] },
  { id: "live-preview", section: "userInterface", anchor: "live-preview-settings", labelKey: "settingsSearch.items.livePreview", fallbackLabel: "Live Preview", keywords: ["preview", "staging", "window", "превью"] },
  { id: "interface", section: "userInterface", labelKey: "settingsSearch.items.interface", fallbackLabel: "Interface appearance and behaviour", keywords: ["interface", "appearance", "window", "tray", "sidebar", "theme", "ui", "интерфейс", "вид", "трей"] },
  { id: "overlay-visibility", section: "userInterface", anchor: "settings-overlay-visibility", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.visibility.label", fallbackLabel: "Show Recording Overlay", groupLabelKey: "settingsSearch.items.overlay", groupFallbackLabel: "Recording overlay", keywords: ["show overlay","hide overlay","recording indicator","показать оверлей","скрыть оверлей","индикатор записи"] },
  { id: "overlay-position", section: "userInterface", anchor: "settings-overlay-position", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.title", fallbackLabel: "Overlay Position", groupLabelKey: "settingsSearch.items.overlay", groupFallbackLabel: "Recording overlay", keywords: ["overlay position","placement","move","coordinates","custom x","custom y","monitor","taskbar","позиция оверлея","координаты","монитор"] },
  { id: "overlay-reserved-areas", section: "userInterface", anchor: "settings-overlay-reserved-areas", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.allowReservedAreas.label", fallbackLabel: "Allow Auto-Positioning in Reserved Areas", groupLabelKey: "settingsSearch.items.overlay", groupFallbackLabel: "Recording overlay", keywords: ["taskbar","dock","weather","reserved areas","панель задач","док","область погоды"] },
  { id: "overlay-entrance-animation", section: "userInterface", anchor: "settings-overlay-entrance-animation", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.entranceAnimation.label", fallbackLabel: "Overlay Entrance Animation", groupLabelKey: "settingsSearch.items.overlay", groupFallbackLabel: "Recording overlay", keywords: ["entrance","appear","spring","rise","animation","анимация появления","пружина"] },
  { id: "overlay-exit-animation", section: "userInterface", anchor: "settings-overlay-exit-animation", expandAnchor: "recording-overlay-settings", labelKey: "settings.advanced.overlay.exitAnimation.label", fallbackLabel: "Overlay Exit Animation", groupLabelKey: "settingsSearch.items.overlay", groupFallbackLabel: "Recording overlay", keywords: ["exit","disappear","shrink","blur","portal","animation","анимация исчезновения","портал"] },
] as const satisfies readonly SettingsSearchEntry[];
