import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const postProcessingSearchEntries = [
  { id: "postprocessing", section: "postprocessing", labelKey: "settingsSearch.items.postProcessing", fallbackLabel: "LLM post-processing", keywords: ["llm", "cleanup", "prompt", "post processing", "ai", "постобработка"] },
  { id: "postprocess-prompts", section: "postprocessing", anchor: "settings-postprocess-prompts", labelKey: "settings.postProcessing.prompts.title", fallbackLabel: "Post-Processing Prompts", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["system prompt","user prompt","prompt templates","selected prompt","системный промпт","промпт постобработки","шаблон промпта"] },
  { id: "postprocess-api", section: "postprocessing", anchor: "settings-postprocess-api", labelKey: "settings.postProcessing.api.title", fallbackLabel: "API Configuration", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["llm provider","llm model","llm api key","llm endpoint","base url","openrouter","ollama","lm studio","провайдер llm","ключ llm","адрес api"] },
  { id: "llm-benchmark", section: "postprocessing", anchor: "settings-llm-benchmark", labelKey: "settingsSearch.items.llm-benchmark", fallbackLabel: "LLM Benchmark", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["benchmark","latency benchmark","first token","llm performance","бенчмарк","задержка llm","первый токен"] },
  { id: "postprocess-provider", section: "postprocessing", anchor: "post_processing-llm-provider", labelKey: "settings.postProcessing.api.provider.title", fallbackLabel: "Provider", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["llm provider","openrouter","ollama","lm studio","openai","gemini","провайдер постобработки"] },
  { id: "postprocess-base-url", section: "postprocessing", anchor: "post_processing-llm-base-url", fallbackAnchor: "settings-postprocess-api", labelKey: "settings.postProcessing.api.baseUrl.title", fallbackLabel: "Base URL", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["llm base url","custom endpoint","server url","адрес llm","базовый url"] },
  { id: "postprocess-api-key", section: "postprocessing", anchor: "post_processing-llm-api-key", fallbackAnchor: "settings-postprocess-api", labelKey: "settings.postProcessing.api.apiKey.title", fallbackLabel: "API Key", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["llm api key","provider credential","post processing key","ключ постобработки","ключ провайдера"] },
  { id: "postprocess-model", section: "postprocessing", anchor: "post_processing-llm-model", fallbackAnchor: "settings-postprocess-api", labelKey: "settings.postProcessing.api.model.title", fallbackLabel: "Model", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["llm model","model id","post processing model","модель постобработки","идентификатор модели"] },
  { id: "postprocess-thinking", section: "postprocessing", anchor: "post_process-thinking", fallbackAnchor: "settings-postprocess-api", labelKey: "settings.extendedThinking.title", fallbackLabel: "Extended Thinking", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["thinking","reasoning","extended thinking","размышление","рассуждение"] },
  { id: "postprocess-thinking-budget", section: "postprocessing", anchor: "post_process-thinking-budget", fallbackAnchor: "settings-postprocess-api", labelKey: "settings.extendedThinking.budget.title", fallbackLabel: "Reasoning Budget", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["reasoning budget","thinking tokens","token budget","бюджет рассуждений","токены размышления"] },
  { id: "llm-postprocessing-enabled", section: "postprocessing", anchor: "settings-llm-postprocessing-enabled", labelKey: "settingsSearch.items.llm-postprocessing-enabled", fallbackLabel: "Enable LLM post-processing for active profile", groupLabelKey: "settingsSearch.items.postProcessing", groupFallbackLabel: "LLM post-processing", keywords: ["enable llm","active profile post processing","enable post processing","включить llm","включить постобработку"] },
] as const satisfies readonly SettingsSearchEntry[];
