import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const browserConnectorSearchEntries = [
  { id: "connector", section: "browserConnector", labelKey: "settingsSearch.items.connector", fallbackLabel: "Browser connector", keywords: ["chrome", "browser", "extension", "chatgpt", "claude", "браузер", "коннектор"] },
  { id: "connector-status", section: "browserConnector", anchor: "settings-connector-status", labelKey: "settings.browserConnector.status.sectionTitle", fallbackLabel: "Extension Status", groupLabelKey: "sidebar.browserConnector", groupFallbackLabel: "Connector", keywords: ["extension status","connection status","export extension","install extension","статус расширения","установка расширения"] },
  { id: "connector-dictation", section: "browserConnector", anchor: "settings-connector-dictation", labelKey: "settings.general.shortcut.bindings.send_to_extension.name", fallbackLabel: "Send Transcription Directly to Extension", groupLabelKey: "sidebar.browserConnector", groupFallbackLabel: "Connector", keywords: ["send dictation","extension shortcut","browser transcription","отправить диктовку","шорткат расширения"] },
  { id: "connector-selection", section: "browserConnector", anchor: "settings-connector-selection", labelKey: "settings.general.shortcut.bindings.send_to_extension_with_selection.name", fallbackLabel: "Send Transcription + Selection to Extension", groupLabelKey: "sidebar.browserConnector", groupFallbackLabel: "Connector", keywords: ["transcription selection","selected text prompt","quick tap prompt","system prompt","user prompt","диктовка с выделением","промпт выделения"] },
  { id: "connector-screenshot", section: "browserConnector", anchor: "settings-connector-screenshot", labelKey: "settings.general.shortcut.bindings.send_screenshot_to_extension.name", fallbackLabel: "Send Transcription + Screenshot to Extension", groupLabelKey: "sidebar.browserConnector", groupFallbackLabel: "Connector", keywords: ["screenshot","screen capture","native picker","capture command","screenshots folder","screenshot timeout","скриншот","захват экрана","папка скриншотов"] },
  { id: "connector-auto-open", section: "browserConnector", anchor: "settings-connector-auto-open", labelKey: "settings.browserConnector.autoOpen.title", fallbackLabel: "Auto-Open Tab", groupLabelKey: "sidebar.browserConnector", groupFallbackLabel: "Connector", keywords: ["auto open tab","target site","chatgpt tab","claude tab","автоматически открыть вкладку","целевой сайт"] },
] as const satisfies readonly SettingsSearchEntry[];
