import { type as getOsType } from "@tauri-apps/plugin-os";
import type { SettingsSearchEntry } from "../settingsSearchTypes";

const unavailableReasonFallback = "Available on Windows only.";

const isWindows = (() => {
  try {
    return getOsType() === "windows";
  } catch {
    return false;
  }
})();

export const aiReplaceSearchEntries = [
  { id: "ai-replace", section: "aiReplace", labelKey: "settingsSearch.items.aiReplace", fallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback, keywords: ["replace selection", "instruction", "prompt", "замена"] },
  { id: "ai-replace-shortcut", section: "aiReplace", anchor: "shortcut-ai_replace_selection", labelKey: "settings.general.shortcut.bindings.ai_replace_selection.name", fallbackLabel: "AI Replace Selection", groupLabelKey: "settingsSearch.groups.shortcuts", groupFallbackLabel: "Shortcuts", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback, keywords: ["ai replace hotkey", "selected text shortcut", "replace selection", "замена выделения", "горячая клавиша"] },
  { id: "ai-replace-no-selection", section: "aiReplace", anchor: "settings-ai-replace-no-selection", labelKey: "settings.aiReplace.noSelection.title", fallbackLabel: "Without Selection Mode", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["without selection","no selection prompt","allow without selection","без выделения","промпт без выделения"] },
  { id: "ai-replace-quick-tap", section: "aiReplace", anchor: "settings-ai-replace-quick-tap", labelKey: "settings.aiReplace.quickTap.title", fallbackLabel: "Quick Tap Mode", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["quick tap","short press","quick tap prompt","короткое нажатие","быстрое нажатие"] },
  { id: "ai-replace-quick-tap-threshold", section: "aiReplace", anchor: "settings-ai-replace-quick-tap-threshold", fallbackAnchor: "settings-ai-replace-quick-tap", labelKey: "settings.aiReplace.quickTap.threshold.title", fallbackLabel: "Quick Tap Threshold", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["quick tap threshold","tap duration","short press milliseconds","порог короткого нажатия","время нажатия"] },
  { id: "ai-replace-selection-prompts", section: "aiReplace", anchor: "settings-ai-replace-selection-prompts", labelKey: "settings.aiReplace.withSelection.title", fallbackLabel: "With Selection Mode", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["selection prompt","system prompt","user prompt template","instruction","промпт выделения","системный промпт","шаблон промпта"] },
  { id: "ai-replace-max-characters", section: "aiReplace", anchor: "settings-ai-replace-max-characters", labelKey: "settings.aiReplace.withSelection.maxChars.title", fallbackLabel: "Max Characters", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["max characters","selection length","text limit","максимум символов","лимит текста"] },
  { id: "ai-replace-restore-on-error", section: "aiReplace", anchor: "settings-ai-replace-restore-on-error", labelKey: "settings.aiReplace.withSelection.restoreOnError.label", fallbackLabel: "Attempt Restore On Error", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["restore on error","restore selection","undo failed replacement","восстановить при ошибке","восстановление выделения"] },
  { id: "ai-replace-api", section: "aiReplace", anchor: "settings-ai-replace-api", labelKey: "settings.aiReplace.api.title", fallbackLabel: "AI Replace (Text Selection)", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace provider","ai replace model","ai replace api key","ai replace endpoint","провайдер замены","модель замены","ключ замены"] },
  { id: "ai-replace-provider", section: "aiReplace", anchor: "ai_replace-llm-provider", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.postProcessing.api.provider.title", fallbackLabel: "Provider", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace provider","replacement provider","провайдер замены","провайдер ai replace"] },
  { id: "ai-replace-model", section: "aiReplace", anchor: "ai_replace-llm-model", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.postProcessing.api.model.title", fallbackLabel: "Model", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace model","replacement model","модель замены","модель ai replace"] },
  { id: "ai-replace-api-key", section: "aiReplace", anchor: "ai_replace-llm-api-key", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.postProcessing.api.apiKey.title", fallbackLabel: "API Key", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace api key","replacement credential","ключ замены","ключ ai replace"] },
  { id: "ai-replace-base-url", section: "aiReplace", anchor: "ai_replace-llm-base-url", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.postProcessing.api.baseUrl.title", fallbackLabel: "Base URL", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace endpoint","replacement base url","адрес замены","адрес ai replace"] },
  { id: "ai-replace-thinking", section: "aiReplace", anchor: "ai_replace-thinking", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.extendedThinking.title", fallbackLabel: "Extended Thinking", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace thinking","replacement reasoning","размышление ai replace","рассуждение при замене"] },
  { id: "ai-replace-thinking-budget", section: "aiReplace", anchor: "ai_replace-thinking-budget", fallbackAnchor: "settings-ai-replace-api", labelKey: "settings.extendedThinking.budget.title", fallbackLabel: "Reasoning Budget", groupLabelKey: "sidebar.aiReplace", groupFallbackLabel: "AI Replace", unavailableReasonKey: "settingsSearch.unavailable.windowsOnly", unavailableReasonFallback: "Available on Windows only.", isAvailable: () => isWindows, keywords: ["ai replace reasoning budget","replacement token budget","бюджет рассуждений ai replace","токены замены"] },
] as const satisfies readonly SettingsSearchEntry[];
