import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const generalSearchEntries = [
  { id: "microphone", section: "general", labelKey: "settingsSearch.items.microphone", fallbackLabel: "Microphone and dictation shortcut", groupLabelKey: "settingsSearch.groups.audioAndShortcuts", groupFallbackLabel: "Audio & shortcuts", keywords: ["mic", "input device", "shortcut", "hotkey", "microphone", "микрофон", "шорткат"] },
  { id: "profiles", section: "general", labelKey: "settingsSearch.items.profiles", fallbackLabel: "Transcription profiles", groupLabelKey: "settingsSearch.groups.profiles", groupFallbackLabel: "Profiles", keywords: ["profile", "model override", "dictation", "профиль", "диктовка"] },
  { id: "active-profile-shortcut", section: "general", anchor: "shortcut-transcribe", labelKey: "settings.transcriptionProfiles.transcribeActiveProfile", fallbackLabel: "Transcribe with Active Profile", groupLabelKey: "settingsSearch.groups.shortcuts", groupFallbackLabel: "Shortcuts", keywords: ["dictation shortcut", "active profile hotkey", "transcribe", "диктовка", "активный профиль", "горячая клавиша"] },
  { id: "cycle-profile-shortcut", section: "general", anchor: "shortcut-cycle_profile", labelKey: "settings.transcriptionProfiles.cycleActiveProfilesShort", fallbackLabel: "Global shortcut to cycle through active profiles", groupLabelKey: "settingsSearch.groups.shortcuts", groupFallbackLabel: "Shortcuts", keywords: ["cycle profile", "switch profile", "profile shortcut", "переключить профиль", "цикл профилей", "горячая клавиша"] },
  { id: "default-profile", section: "general", anchor: "transcription-profile-default", labelKey: "settings.transcriptionProfiles.defaultProfile", fallbackLabel: "Default (Global)", groupLabelKey: "settingsSearch.groups.profiles", groupFallbackLabel: "Profiles", keywords: ["default profile", "global profile", "language", "model", "профиль по умолчанию", "глобальный профиль"] },
] as const satisfies readonly SettingsSearchEntry[];
