import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const generalSearchEntries = [
  { id: "microphone", section: "general", labelKey: "settingsSearch.items.microphone", fallbackLabel: "Microphone and dictation shortcut", groupLabelKey: "settingsSearch.groups.audioAndShortcuts", groupFallbackLabel: "Audio & shortcuts", keywords: ["mic", "input device", "shortcut", "hotkey", "microphone", "микрофон", "шорткат"] },
  { id: "profiles", section: "general", labelKey: "settingsSearch.items.profiles", fallbackLabel: "Transcription profiles", groupLabelKey: "settingsSearch.groups.profiles", groupFallbackLabel: "Profiles", keywords: ["profile", "model override", "dictation", "профиль", "диктовка"] },
  { id: "active-profile-shortcut", section: "general", anchor: "shortcut-transcribe", labelKey: "settings.transcriptionProfiles.transcribeActiveProfile", fallbackLabel: "Transcribe with Active Profile", groupLabelKey: "settingsSearch.groups.shortcuts", groupFallbackLabel: "Shortcuts", keywords: ["dictation shortcut", "active profile hotkey", "transcribe", "диктовка", "активный профиль", "горячая клавиша"] },
  { id: "cycle-profile-shortcut", section: "general", anchor: "shortcut-cycle_profile", labelKey: "settings.transcriptionProfiles.cycleActiveProfilesShort", fallbackLabel: "Global shortcut to cycle through active profiles", groupLabelKey: "settingsSearch.groups.shortcuts", groupFallbackLabel: "Shortcuts", keywords: ["cycle profile", "switch profile", "profile shortcut", "переключить профиль", "цикл профилей", "горячая клавиша"] },
  { id: "default-profile", section: "general", anchor: "transcription-profile-default", labelKey: "settings.transcriptionProfiles.defaultProfile", fallbackLabel: "Default (Global)", groupLabelKey: "settingsSearch.groups.profiles", groupFallbackLabel: "Profiles", keywords: ["default profile", "global profile", "language", "model", "профиль по умолчанию", "глобальный профиль"] },
  { id: "microphone-device", section: "general", anchor: "settings-microphone-device", labelKey: "settings.sound.microphone.title", fallbackLabel: "Microphone", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["input device","recording device","audio input","mic","микрофон","устройство ввода"] },
  { id: "input-channel", section: "general", anchor: "settings-input-channel", labelKey: "settings.sound.channel.title", fallbackLabel: "Input Channel", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["channel","left channel","right channel","stereo","mono","канал","стерео","моно"] },
  { id: "microphone-boost", section: "general", anchor: "settings-microphone-boost", labelKey: "settings.sound.microphone.boost.title", fallbackLabel: "Microphone Input Boost", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["gain","boost","amplification","quiet microphone","усиление","тихий микрофон","громкость микрофона"] },
  { id: "microphone-noise-cancellation", section: "general", anchor: "settings-microphone-noise-cancellation", labelKey: "settings.sound.microphone.noiseCancellation.title", fallbackLabel: "Noise Cancellation", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["rnnoise","denoise","noise cancellation","background noise","шумоподавление","фоновый шум"] },
  { id: "microphone-auto-switch", section: "general", anchor: "settings-microphone-auto-switch", labelKey: "settings.sound.microphone.autoSelect.label", fallbackLabel: "Auto-select by microphone name mask", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["automatic microphone","auto switch","device switching","автоматический микрофон","переключение микрофона"] },
  { id: "microphone-name-mask", section: "general", anchor: "settings-microphone-name-mask", labelKey: "settings.sound.microphone.autoSelectMask.title", fallbackLabel: "Microphone Name Mask", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["microphone mask","name pattern","wildcard","маска микрофона","шаблон имени"] },
  { id: "recording-feedback", section: "general", anchor: "settings-recording-feedback", labelKey: "settings.sound.audioFeedback.label", fallbackLabel: "Recording start/stop sounds", groupLabelKey: "settings.sound.title", groupFallbackLabel: "Sound", keywords: ["audio feedback","beep","start sound","stop sound","recording cue","звуковой сигнал","звук начала","звук остановки"] },
] as const satisfies readonly SettingsSearchEntry[];
