import type { SettingsSearchEntry } from "../settingsSearchTypes";
import { globalSttSelection, sttSupports } from "../../../lib/sttModelSelection";

export const transcribeFileSearchEntries = [
  { id: "file-model", section: "transcribeFile", anchor: "transcribe-file-model-settings", labelKey: "settingsSearch.items.fileModel", fallbackLabel: "File transcription model and settings", groupLabelKey: "settingsSearch.groups.modelAndLanguage", groupFallbackLabel: "Model & language", keywords: ["transcribe file", "audio file", "video file", "model", "chunking", "language hints", "транскрибация файла"] },
  { id: "file-diarization", section: "transcribeFile", anchor: "transcribe-file-diarization", expandAnchor: "transcribe-file-model-settings", labelKey: "settingsSearch.items.fileDiarization", fallbackLabel: "File transcription speaker diarization", groupLabelKey: "settingsSearch.groups.modelAndLanguage", groupFallbackLabel: "Model & language", unavailableReasonKey: "settingsSearch.unavailable.diarization", unavailableReasonFallback: "Select a model or provider that supports speaker diarization.", isAvailable: (settings) => !settings || sttSupports(((settings as any).file_transcription_model_selection ?? globalSttSelection(settings)), "diarization", "file"), keywords: ["diarization", "speaker", "file", "диаризация", "спикер", "файл"] },
  { id: "file-transcription-input", section: "transcribeFile", anchor: "settings-file-transcription-input", labelKey: "transcribeFile.stages.file", fallbackLabel: "File", keywords: ["drop audio","open audio file","video file","select file","открыть аудио","выбрать файл"] },
  { id: "file-transcription-result", section: "transcribeFile", anchor: "settings-file-transcription-result", labelKey: "transcribeFile.stages.result", fallbackLabel: "Result", keywords: ["output file","save transcript","srt","vtt","subtitles","output format","экспорт транскрипта","субтитры","результат"] },
  { id: "file-output-format", section: "transcribeFile", anchor: "settings-file-output-format", fallbackAnchor: "transcribe-file-model-settings", labelKey: "transcribeFile.outputFormat.label", fallbackLabel: "Output Format", keywords: ["output format","srt","vtt","subtitles","text file","формат вывода","субтитры"] },
] as const satisfies readonly SettingsSearchEntry[];
