import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const textReplacementSearchEntries = [
  { id: "decapitalize-after-edit", section: "textReplacement", anchor: "decapitalize-after-edit-settings", labelKey: "settingsSearch.items.decapitalizeAfterEdit", fallbackLabel: "Decapitalize after manual edit", keywords: ["de", "dec", "decap", "decapitalize", "decapitalization", "lowercase", "lower case", "capitalization", "case", "декапитализация", "строчная буква", "нижний регистр", "регистр"] },
  { id: "custom-words", section: "textReplacement", anchor: "custom-words-settings", labelKey: "settingsSearch.items.customWords", fallbackLabel: "Custom Words", groupLabelKey: "settingsSearch.groups.vocabulary", groupFallbackLabel: "Vocabulary", keywords: ["vocabulary", "dictionary", "correction", "replacement", "словарь", "замена слов"] },
  { id: "text-processing", section: "textReplacement", labelKey: "settingsSearch.items.textProcessing", fallbackLabel: "Text replacement and processing", keywords: ["replacement", "regex", "fuzzy", "correction", "обработка текста"] },
  { id: "text-replacement-enabled", section: "textReplacement", anchor: "settings-text-replacement-enabled", labelKey: "textReplacement.enable", fallbackLabel: "Enable Text Replacement", keywords: ["enable replacements","replacement rules","text replacement","замены текста","правила замены"] },
  { id: "text-replacement-before-llm", section: "textReplacement", anchor: "settings-text-replacement-before-llm", labelKey: "textReplacement.beforeLlm", fallbackLabel: "Apply Before LLM Post-Processing", keywords: ["before llm","replacement order","before post processing","до llm","порядок обработки"] },
  { id: "filler-word-filter", section: "textReplacement", anchor: "settings-filler-word-filter", labelKey: "audioProcessing.fillerFilter", fallbackLabel: "Remove Filler Words", keywords: ["filler words","uh","um","hmm","speech cleanup","слова паразиты","очистка речи"] },
  { id: "invisible-character-filter", section: "textReplacement", anchor: "settings-invisible-character-filter", labelKey: "audioProcessing.zeroWidthFilter", fallbackLabel: "Strip Invisible Characters", keywords: ["zero width","invisible characters","unicode cleanup","невидимые символы","нулевая ширина"] },
  { id: "fuzzy-word-correction", section: "textReplacement", anchor: "settings-fuzzy-word-correction", labelKey: "textReplacement.fuzzyWordCorrectionTitle", fallbackLabel: "Fuzzy Word Correction", keywords: ["phonetic correction","levenshtein","fuzzy matching","misheard words","фонетическая коррекция","нечеткая коррекция"] },
  { id: "multi-word-correction", section: "textReplacement", anchor: "settings-multi-word-correction", labelKey: "textReplacement.multiWordMatchingLabel", fallbackLabel: "Enable Multi-word Matching (N-grams)", keywords: ["ngram","n gram","multi word","phrases","многословное сопоставление","фразы"] },
  { id: "word-correction-sensitivity", section: "textReplacement", anchor: "settings-word-correction-sensitivity", labelKey: "textReplacement.correctionSensitivityLabel", fallbackLabel: "Correction Sensitivity", keywords: ["correction threshold","fuzzy sensitivity","aggressive correction","порог коррекции","чувствительность исправлений"] },
  { id: "output-whitespace", section: "textReplacement", anchor: "settings-output-whitespace", labelKey: "textReplacement.outputWhitespaceTitle", fallbackLabel: "Output Whitespace", keywords: ["whitespace","leading space","trailing space","пробелы","начальный пробел","конечный пробел"] },
  { id: "leading-space-remove", section: "textReplacement", anchor: "settings-leading-space-remove", labelKey: "textReplacement.outputWhitespaceLeadingRemoveLabel", fallbackLabel: "Remove leading space if provider returned one", keywords: ["remove leading space","trim start","удалить начальный пробел","пробел в начале"] },
  { id: "leading-space-add", section: "textReplacement", anchor: "settings-leading-space-add", labelKey: "textReplacement.outputWhitespaceLeadingAddLabel", fallbackLabel: "Add leading space if provider did not return one", keywords: ["add leading space","prepend space","добавить начальный пробел","пробел перед текстом"] },
  { id: "trailing-space-remove", section: "textReplacement", anchor: "settings-trailing-space-remove", labelKey: "textReplacement.outputWhitespaceTrailingRemoveLabel", fallbackLabel: "Remove trailing space if provider returned one", keywords: ["remove trailing space","trim end","удалить конечный пробел","пробел в конце"] },
  { id: "trailing-space-add", section: "textReplacement", anchor: "settings-trailing-space-add", labelKey: "textReplacement.outputWhitespaceTrailingAddLabel", fallbackLabel: "Add trailing space if provider did not return one", keywords: ["add trailing space","append space","добавить конечный пробел","пробел после текста"] },
  { id: "soniox-chunk-correction", section: "textReplacement", anchor: "settings-soniox-chunk-correction", labelKey: "textReplacement.sonioxRealtimeChunkFuzzyLabel", fallbackLabel: "Enable Fuzzy Word Correction for Soniox Live Chunks", keywords: ["soniox chunks","realtime fuzzy correction","streaming correction","исправление live фрагментов","коррекция soniox"] },
  { id: "soniox-chunk-safety-buffer", section: "textReplacement", anchor: "settings-soniox-chunk-safety-buffer", labelKey: "textReplacement.sonioxRealtimeChunkSafetyBufferLabel", fallbackLabel: "Keep Safety Buffer for Cross-chunk Matching", keywords: ["cross chunk","safety buffer","chunk boundary","между фрагментами","буфер безопасности"] },
  { id: "decapitalize-secondary-key", section: "textReplacement", anchor: "settings-decapitalize-secondary-key", expandAnchor: "decapitalize-after-edit-settings", labelKey: "textReplacement.decapitalizeAfterEditSecondaryKeyEnableLabel", fallbackLabel: "Enable Secondary Monitored Key (OR)", keywords: ["secondary decapitalize","second key","or key","вторая клавиша","второй триггер"] },
] as const satisfies readonly SettingsSearchEntry[];
