import type { SettingsSearchEntry } from "../settingsSearchTypes";

export const textReplacementSearchEntries = [
  { id: "decapitalize-after-edit", section: "textReplacement", anchor: "decapitalize-after-edit-settings", labelKey: "settingsSearch.items.decapitalizeAfterEdit", fallbackLabel: "Decapitalize after manual edit", keywords: ["de", "dec", "decap", "decapitalize", "decapitalization", "lowercase", "lower case", "capitalization", "case", "декапитализация", "строчная буква", "нижний регистр", "регистр"] },
  { id: "custom-words", section: "textReplacement", anchor: "custom-words-settings", labelKey: "settingsSearch.items.customWords", fallbackLabel: "Custom Words", groupLabelKey: "settingsSearch.groups.vocabulary", groupFallbackLabel: "Vocabulary", keywords: ["vocabulary", "dictionary", "correction", "replacement", "словарь", "замена слов"] },
  { id: "text-processing", section: "textReplacement", labelKey: "settingsSearch.items.textProcessing", fallbackLabel: "Text replacement and processing", keywords: ["replacement", "regex", "fuzzy", "correction", "обработка текста"] },
  { id: "text-replacement-enabled", section: "textReplacement", anchor: "settings-text-replacement-enabled", labelKey: "textReplacement.enable", fallbackLabel: "Enable Text Replacement", keywords: ["enable replacements","replacement rules","text replacement","замены текста","правила замены"] },
  { id: "text-replacement-before-llm", section: "textReplacement", anchor: "settings-text-replacement-before-llm", labelKey: "textReplacement.beforeLlm", fallbackLabel: "Apply Before LLM Post-Processing", keywords: ["before llm","replacement order","before post processing","до llm","порядок обработки"] },
  { id: "filler-word-filter", section: "textReplacement", anchor: "settings-filler-word-filter", labelKey: "audioProcessing.fillerFilter", fallbackLabel: "Remove Filler Words", keywords: ["filler words","uh","um","hmm","speech cleanup","слова паразиты","очистка речи"] },
  { id: "invisible-character-filter", section: "textReplacement", anchor: "settings-invisible-character-filter", labelKey: "audioProcessing.zeroWidthFilter", fallbackLabel: "Strip Invisible Characters", keywords: ["zero width","invisible characters","unicode cleanup","невидимые символы","нулевая ширина"] },
  { id: "fuzzy-word-correction", section: "textReplacement", anchor: "settings-fuzzy-word-correction", labelKey: "textReplacement.fuzzyWordCorrectionTitle", fallbackLabel: "Fuzzy Word Correction", keywords: ["phonetic correction","levenshtein","fuzzy matching","misheard words","фонетическая коррекция","нечеткая коррекция"] },
  { id: "multi-word-correction", section: "textReplacement", anchor: "settings-multi-word-correction", labelKey: "textReplacement.multiWordMatchingLabel", fallbackLabel: "Enable Multi-word Matching (N-grams)", keywords: ["ngram","n gram","multi word","phrases","многословное сопоставление","фразы"] },
  { id: "word-correction-sensitivity", section: "textReplacement", anchor: "settings-word-correction-sensitivity", labelKey: "textReplacement.correctionSensitivityLabel", fallbackLabel: "Correction Sensitivity", keywords: ["correction threshold","fuzzy sensitivity","aggressive correction","порог коррекции","чувствительность исправлений"] },
] as const satisfies readonly SettingsSearchEntry[];
