import { type as getOsType } from "@tauri-apps/plugin-os";
import type { AppSettings } from "@/bindings";
import type { SettingsSearchEntry } from "../settingsSearchTypes";

const API_KEY_PROVIDERS = new Set([
  "soniox",
  "deepgram",
  "openai",
  "openai_compatible",
  "murf",
  "elevenlabs",
  "cartesia",
]);
const LOCAL_MODEL_PROVIDERS = new Set(["local_qwen", "local_kokoro"]);
const selectedProvider = (settings: AppSettings | null) =>
  settings?.tts?.provider ?? "soniox";
const selectedProviderRequiresApiKey = (settings: AppSettings | null) =>
  API_KEY_PROVIDERS.has(selectedProvider(settings));
const selectedProviderHasLocalModel = (settings: AppSettings | null) =>
  LOCAL_MODEL_PROVIDERS.has(selectedProvider(settings));
const isWindows = (() => {
  try {
    return getOsType() === "windows";
  } catch {
    return false;
  }
})();

export const textToSpeechSearchEntries = [
  {
    id: "tts",
    section: "textToSpeech",
    anchor: "tts-provider-settings",
    labelKey: "settingsSearch.items.tts",
    fallbackLabel: "Text-to-speech setup",
    groupLabelKey: "settingsSearch.groups.setup",
    groupFallbackLabel: "Setup",
    keywords: [
      "tts",
      "text to speech",
      "speak selected text",
      "enable tts",
      "provider",
      "soniox",
      "deepgram",
      "openai",
      "murf",
      "elevenlabs",
      "cartesia",
      "edge tts",
      "qwen",
      "kokoro",
      "windows voice",
      "озвучить выделенный текст",
      "синтез речи",
      "провайдер",
    ],
  },
  {
    id: "tts-actions",
    section: "textToSpeech",
    anchor: "tts-actions",
    labelKey: "textToSpeech.actions.title",
    fallbackLabel: "Global read actions and keys that summon them",
    groupLabelKey: "settingsSearch.groups.shortcuts",
    groupFallbackLabel: "Shortcuts",
    keywords: [
      "listen later",
      "queue",
      "global read action",
      "hotkey",
      "shortcut",
      "очередь",
      "прочитать позже",
      "горячая клавиша",
    ],
  },
  {
    id: "tts-read-clipboard",
    section: "textToSpeech",
    anchor: "shortcut-read_clipboard",
    labelKey: "textToSpeech.actions.readClipboardTitle",
    fallbackLabel: "Read clipboard",
    groupLabelKey: "settingsSearch.groups.shortcuts",
    groupFallbackLabel: "Shortcuts",
    keywords: [
      "clipboard tts",
      "read clipboard shortcut",
      "speak clipboard",
      "озвучить буфер обмена",
      "прочитать буфер",
      "горячая клавиша",
    ],
  },
  {
    id: "tts-read-selection",
    section: "textToSpeech",
    anchor: "shortcut-read_selection_tts",
    labelKey: "textToSpeech.actions.readSelectionTitle",
    fallbackLabel: "Copy selected text, then read clipboard",
    groupLabelKey: "settingsSearch.groups.shortcuts",
    groupFallbackLabel: "Shortcuts",
    keywords: [
      "selected text tts",
      "read selection shortcut",
      "copy and speak",
      "speak selected",
      "озвучить выделенный текст",
      "прочитать выделение",
    ],
  },
  {
    id: "tts-read-selection-direct",
    section: "textToSpeech",
    anchor: "shortcut-read_selection_direct_tts",
    labelKey: "textToSpeech.actions.readSelectionDirectTitle",
    fallbackLabel: "Read selected text without copying",
    groupLabelKey: "settingsSearch.groups.shortcuts",
    groupFallbackLabel: "Shortcuts",
    unavailableReasonKey: "settingsSearch.unavailable.windowsOnly",
    unavailableReasonFallback: "Available on Windows only.",
    isAvailable: () => isWindows,
    keywords: [
      "direct selection tts",
      "speak selected text",
      "read without clipboard",
      "windows accessibility",
      "озвучить выделение",
      "без буфера обмена",
    ],
  },
  {
    id: "tts-history-fallback-shortcut",
    section: "textToSpeech",
    anchor: "shortcut-tts_play_history_fallback",
    labelKey: "textToSpeech.overlay.historyFallbackLabel",
    fallbackLabel: "Use Play / Pause when the overlay is closed",
    groupLabelKey: "settingsSearch.groups.shortcuts",
    groupFallbackLabel: "Shortcuts",
    keywords: [
      "tts history hotkey",
      "global play pause",
      "overlay closed",
      "replay newest",
      "история tts горячая клавиша",
      "воспроизведение пауза",
      "оверлей закрыт",
    ],
  },
  {
    id: "tts-gallery",
    section: "textToSpeech",
    anchor: "tts-voice-gallery",
    expandAnchor: "tts-voice-gallery",
    labelKey: "textToSpeech.voiceGallery.title",
    fallbackLabel: "Voices gallery",
    groupLabelKey: "settingsSearch.groups.providerAndVoice",
    groupFallbackLabel: "Provider & voice",
    keywords: [
      "voice samples",
      "preview voices",
      "listen voice",
      "gallery",
      "примеры голосов",
      "прослушать голос",
      "галерея",
    ],
  },
  {
    id: "tts-presets",
    section: "textToSpeech",
    anchor: "tts-synthesis-presets",
    labelKey: "textToSpeech.synthesisPresets.title",
    fallbackLabel: "Presets of all settings",
    groupLabelKey: "settingsSearch.groups.setup",
    groupFallbackLabel: "Setup",
    keywords: [
      "tts preset",
      "save settings",
      "load settings",
      "recommended preset",
      "пресет синтеза",
      "сохранить настройки",
      "загрузить пресет",
    ],
  },
  {
    id: "tts-local-model",
    section: "textToSpeech",
    anchor: "tts-local-model",
    labelKey: "textToSpeech.local.title",
    fallbackLabel: "Local TTS model",
    groupLabelKey: "settingsSearch.groups.models",
    groupFallbackLabel: "Models",
    unavailableReasonKey: "settingsSearch.unavailable.ttsLocalModel",
    unavailableReasonFallback:
      "Select Qwen or Kokoro as the TTS provider to configure its local model.",
    isAvailable: selectedProviderHasLocalModel,
    keywords: [
      "qwen",
      "kokoro",
      "offline voice",
      "local tts",
      "download model",
      "install runtime",
      "license",
      "локальная модель",
      "офлайн голос",
      "скачать модель",
    ],
  },
  {
    id: "tts-voice-settings",
    section: "textToSpeech",
    anchor: "tts-voice-settings",
    labelKey: "settingsSearch.items.ttsVoiceSettings",
    fallbackLabel: "Model, voice, language, and delivery",
    groupLabelKey: "settingsSearch.groups.providerAndVoice",
    groupFallbackLabel: "Provider & voice",
    keywords: [
      "model",
      "voice id",
      "language",
      "locale",
      "speed",
      "rate",
      "pitch",
      "style",
      "emotion",
      "stability",
      "similarity",
      "speaker boost",
      "normalization",
      "voice instructions",
      "prompt",
      "voice catalog",
      "refresh voices",
      "provider voices",
      "модель",
      "голос",
      "язык",
      "скорость",
      "тон",
      "стиль",
      "эмоция",
      "каталог голосов",
      "обновить голоса",
    ],
  },
  {
    id: "tts-playback",
    section: "textToSpeech",
    anchor: "tts-playback-settings",
    labelKey: "textToSpeech.playback.title",
    fallbackLabel: "Playback processing",
    groupLabelKey: "settingsSearch.groups.playback",
    groupFallbackLabel: "Playback",
    keywords: [
      "playback pitch",
      "playback effect",
      "radio effect",
      "retro effect",
      "sound effect",
      "воспроизведение",
      "высота тона",
      "эффект радио",
      "ретро",
    ],
  },
  {
    id: "tts-overlay",
    section: "textToSpeech",
    anchor: "tts-overlay-settings",
    labelKey: "textToSpeech.overlay.title",
    fallbackLabel: "TTS overlay",
    groupLabelKey: "settingsSearch.groups.playback",
    groupFallbackLabel: "Playback",
    keywords: [
      "autoplay",
      "auto hide",
      "play pause key",
      "stop key",
      "playback controls",
      "оверлей tts",
      "автовоспроизведение",
      "автоскрытие",
      "пауза",
      "стоп",
    ],
  },
  {
    id: "tts-ai-cleanup",
    section: "textToSpeech",
    anchor: "tts-interactive-ai-cleanup",
    expandAnchor: "tts-interactive-ai-cleanup",
    labelKey: "textToSpeech.aiCleanup.title",
    fallbackLabel: "AI text cleanup",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "llm cleanup",
      "ai preprocessing",
      "cleanup prompt",
      "ai cleanup api key",
      "llm api key",
      "groq key",
      "gemini key",
      "temperature",
      "max tokens",
      "provider model",
      "очистка текста ии",
      "llm обработка",
      "промпт очистки",
      "api ключ очистки",
    ],
  },
  {
    id: "tts-ai-cleanup-benchmark",
    section: "textToSpeech",
    anchor: "tts-interactive-ai-cleanup-benchmark",
    expandAnchor: "tts-interactive-ai-cleanup",
    labelKey: "textToSpeech.aiCleanup.benchmarkTitle",
    fallbackLabel: "Test and benchmark AI cleanup",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "test cleanup",
      "benchmark llm",
      "latency",
      "sample text",
      "compare output",
      "тест очистки",
      "бенчмарк llm",
      "задержка",
    ],
  },
  {
    id: "tts-preprocessing",
    section: "textToSpeech",
    anchor: "tts-preprocessing-settings",
    labelKey: "settingsSearch.items.ttsPreprocessing",
    fallbackLabel: "TTS text replacement rules",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "preprocessing",
      "replacement rule",
      "regex",
      "remove advertisements",
      "page numbers",
      "before voiceover",
      "предобработка tts",
      "правила замены",
      "регулярное выражение",
      "удалить рекламу",
    ],
  },
  {
    id: "tts-chunking",
    section: "textToSpeech",
    anchor: "tts-chunking-settings",
    labelKey: "textToSpeech.chunking.title",
    fallbackLabel: "Chunking, retries, and pauses",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "chunk size",
      "target characters",
      "retry count",
      "retry delay",
      "pause between chunks",
      "paragraph pause",
      "чанк",
      "повтор запроса",
      "пауза между абзацами",
    ],
  },
  {
    id: "tts-api",
    section: "textToSpeech",
    anchor: "tts-api-settings",
    labelKey: "textToSpeech.api.title",
    fallbackLabel: "API settings for TTS",
    groupLabelKey: "settingsSearch.groups.api",
    groupFallbackLabel: "API",
    unavailableReasonKey: "settingsSearch.unavailable.ttsApiKey",
    unavailableReasonFallback:
      "The selected TTS provider does not use an API key.",
    isAvailable: selectedProviderRequiresApiKey,
    keywords: [
      "api key",
      "credential",
      "shared key",
      "separate key",
      "openai compatible",
      "base url",
      "insecure http",
      "ключ api",
      "учетные данные",
      "общий ключ",
      "отдельный ключ",
      "базовый url",
    ],
  },
  {
    id: "tts-interactive-history",
    section: "textToSpeech",
    anchor: "tts-interactive-history",
    labelKey: "textToSpeech.history.scopes.interactive.title",
    fallbackLabel: "Interactive TTS History",
    groupLabelKey: "settingsSearch.groups.history",
    groupFallbackLabel: "History",
    keywords: [
      "tts history",
      "retain audio",
      "replay",
      "regenerate",
      "export",
      "comparison",
      "storage limit",
      "история tts",
      "повторить аудио",
      "пересоздать",
      "экспорт",
      "хранилище",
    ],
  },
  {
    id: "tts-files",
    section: "ttsFiles",
    anchor: "tts-file-provider-settings",
    labelKey: "settingsSearch.items.ttsFiles",
    fallbackLabel: "Text file to MP3",
    groupLabelKey: "settingsSearch.groups.setup",
    groupFallbackLabel: "Setup",
    keywords: [
      "tts file",
      "text to audio",
      "markdown to audio",
      "file provider",
      "soniox",
      "deepgram",
      "openai",
      "murf",
      "elevenlabs",
      "cartesia",
      "edge tts",
      "qwen",
      "kokoro",
      "windows voice",
      "текст в аудио",
      "markdown в аудио",
      "провайдер файла",
    ],
  },
  {
    id: "tts-files-gallery",
    section: "ttsFiles",
    anchor: "tts-voice-gallery",
    expandAnchor: "tts-voice-gallery",
    labelKey: "textToSpeech.voiceGallery.title",
    fallbackLabel: "Voices gallery",
    groupLabelKey: "settingsSearch.groups.providerAndVoice",
    groupFallbackLabel: "Provider & voice",
    keywords: [
      "voice samples",
      "preview voices",
      "listen voice",
      "gallery",
      "примеры голосов",
      "прослушать голос",
      "галерея",
    ],
  },
  {
    id: "tts-files-unfinished",
    section: "ttsFiles",
    anchor: "tts-unfinished-conversions",
    labelKey: "textToSpeech.unfinishedJobs.title",
    fallbackLabel: "Unfinished conversions",
    groupLabelKey: "settingsSearch.groups.conversion",
    groupFallbackLabel: "Conversion",
    keywords: [
      "resume conversion",
      "interrupted job",
      "partial audio",
      "saved progress",
      "discard conversion",
      "продолжить преобразование",
      "прерванная задача",
      "частичное аудио",
      "сохраненный прогресс",
    ],
  },
  {
    id: "tts-files-conversion",
    section: "ttsFiles",
    anchor: "tts-file-conversion",
    labelKey: "textToSpeech.conversion.title",
    fallbackLabel: "Convert text file to audio",
    groupLabelKey: "settingsSearch.groups.conversion",
    groupFallbackLabel: "Conversion",
    keywords: [
      "choose text file",
      "txt",
      "markdown",
      "output file",
      "start conversion",
      "pause conversion",
      "cli tts",
      "выбрать текстовый файл",
      "выходной файл",
      "начать преобразование",
      "cli",
    ],
  },
  {
    id: "tts-files-output-format",
    section: "ttsFiles",
    anchor: "tts-file-output-format",
    labelKey: "textToSpeech.conversion.finalFormatTitle",
    fallbackLabel: "Final audio format and bitrate",
    groupLabelKey: "settingsSearch.groups.conversion",
    groupFallbackLabel: "Conversion",
    keywords: [
      "mp3",
      "opus",
      "ogg opus",
      "wav",
      "bitrate",
      "audio format",
      "формат аудио",
      "битрейт",
    ],
  },
  {
    id: "tts-files-batch",
    section: "ttsFiles",
    anchor: "tts-batch-conversion",
    labelKey: "textToSpeech.batch.title",
    fallbackLabel: "Batch convert text files",
    groupLabelKey: "settingsSearch.groups.conversion",
    groupFallbackLabel: "Conversion",
    keywords: [
      "batch conversion",
      "multiple files",
      "folder scan",
      "include subfolders",
      "пакетное преобразование",
      "несколько файлов",
      "сканировать папку",
      "подпапки",
    ],
  },
  {
    id: "tts-files-folder-automation",
    section: "ttsFiles",
    anchor: "tts-folder-automation",
    labelKey: "textToSpeech.folder.title",
    fallbackLabel: "Automatic folder conversion",
    groupLabelKey: "settingsSearch.groups.automation",
    groupFallbackLabel: "Automation",
    keywords: [
      "watch folder",
      "automatic conversion",
      "input folder",
      "output folder",
      "settle delay",
      "disk reserve",
      "наблюдение за папкой",
      "автоматическое преобразование",
      "входная папка",
      "резерв диска",
    ],
  },
  {
    id: "tts-files-presets",
    section: "ttsFiles",
    anchor: "tts-synthesis-presets",
    labelKey: "textToSpeech.synthesisPresets.title",
    fallbackLabel: "Presets of all settings",
    groupLabelKey: "settingsSearch.groups.setup",
    groupFallbackLabel: "Setup",
    keywords: [
      "file tts preset",
      "save settings",
      "load settings",
      "shared preset",
      "пресет файла",
      "сохранить настройки",
      "общий пресет",
    ],
  },
  {
    id: "tts-files-local-model",
    section: "ttsFiles",
    anchor: "tts-local-model",
    labelKey: "textToSpeech.local.title",
    fallbackLabel: "Local TTS model",
    groupLabelKey: "settingsSearch.groups.models",
    groupFallbackLabel: "Models",
    unavailableReasonKey: "settingsSearch.unavailable.ttsLocalModel",
    unavailableReasonFallback:
      "Select Qwen or Kokoro as the TTS provider to configure its local model.",
    isAvailable: selectedProviderHasLocalModel,
    keywords: [
      "qwen",
      "kokoro",
      "offline voice",
      "local tts",
      "download model",
      "install runtime",
      "локальная модель",
      "офлайн голос",
      "скачать модель",
    ],
  },
  {
    id: "tts-files-voice-settings",
    section: "ttsFiles",
    anchor: "tts-voice-settings",
    labelKey: "settingsSearch.items.ttsVoiceSettings",
    fallbackLabel: "Model, voice, language, and delivery",
    groupLabelKey: "settingsSearch.groups.providerAndVoice",
    groupFallbackLabel: "Provider & voice",
    keywords: [
      "model",
      "voice id",
      "language",
      "locale",
      "speed",
      "rate",
      "pitch",
      "style",
      "emotion",
      "voice instructions",
      "prompt",
      "voice catalog",
      "refresh voices",
      "provider voices",
      "модель",
      "голос",
      "язык",
      "скорость",
      "тон",
      "стиль",
      "каталог голосов",
      "обновить голоса",
    ],
  },
  {
    id: "tts-files-playback",
    section: "ttsFiles",
    anchor: "tts-playback-settings",
    labelKey: "textToSpeech.playback.title",
    fallbackLabel: "Playback processing",
    groupLabelKey: "settingsSearch.groups.playback",
    groupFallbackLabel: "Playback",
    keywords: [
      "history playback pitch",
      "playback effect",
      "radio effect",
      "retro effect",
      "воспроизведение истории",
      "высота тона",
      "эффект радио",
    ],
  },
  {
    id: "tts-files-ai-cleanup",
    section: "ttsFiles",
    anchor: "tts-files-ai-cleanup",
    expandAnchor: "tts-files-ai-cleanup",
    labelKey: "textToSpeech.aiCleanup.title",
    fallbackLabel: "AI text cleanup",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "llm cleanup",
      "ai preprocessing",
      "cleanup prompt",
      "ai cleanup api key",
      "llm api key",
      "groq key",
      "gemini key",
      "temperature",
      "max tokens",
      "provider model",
      "очистка текста ии",
      "llm обработка",
      "промпт очистки",
      "api ключ очистки",
    ],
  },
  {
    id: "tts-files-ai-cleanup-benchmark",
    section: "ttsFiles",
    anchor: "tts-files-ai-cleanup-benchmark",
    expandAnchor: "tts-files-ai-cleanup",
    labelKey: "textToSpeech.aiCleanup.benchmarkTitle",
    fallbackLabel: "Test and benchmark AI cleanup",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "test cleanup",
      "benchmark llm",
      "latency",
      "sample text",
      "compare output",
      "тест очистки",
      "бенчмарк llm",
      "задержка",
    ],
  },
  {
    id: "tts-files-preprocessing",
    section: "ttsFiles",
    anchor: "tts-preprocessing-settings",
    labelKey: "settingsSearch.items.ttsPreprocessing",
    fallbackLabel: "TTS text replacement rules",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "preprocessing",
      "replacement rule",
      "regex",
      "remove advertisements",
      "page numbers",
      "before voiceover",
      "предобработка tts",
      "правила замены",
      "регулярное выражение",
    ],
  },
  {
    id: "tts-files-chunking",
    section: "ttsFiles",
    anchor: "tts-chunking-settings",
    labelKey: "textToSpeech.chunking.title",
    fallbackLabel: "Chunking, retries, and pauses",
    groupLabelKey: "settingsSearch.groups.processing",
    groupFallbackLabel: "Processing",
    keywords: [
      "file chunk size",
      "target characters",
      "retry count",
      "retry delay",
      "pause between chunks",
      "paragraph pause",
      "размер чанка файла",
      "повтор запроса",
      "пауза между абзацами",
    ],
  },
  {
    id: "tts-files-api",
    section: "ttsFiles",
    anchor: "tts-api-settings",
    labelKey: "textToSpeech.api.title",
    fallbackLabel: "API settings for TTS",
    groupLabelKey: "settingsSearch.groups.api",
    groupFallbackLabel: "API",
    unavailableReasonKey: "settingsSearch.unavailable.ttsApiKey",
    unavailableReasonFallback:
      "The selected TTS provider does not use an API key.",
    isAvailable: selectedProviderRequiresApiKey,
    keywords: [
      "api key",
      "credential",
      "shared key",
      "separate key",
      "openai compatible",
      "base url",
      "ключ api",
      "учетные данные",
      "общий ключ",
      "отдельный ключ",
    ],
  },
  {
    id: "tts-files-history",
    section: "ttsFiles",
    anchor: "tts-file-history",
    labelKey: "textToSpeech.history.scopes.file.title",
    fallbackLabel: "File TTS History",
    groupLabelKey: "settingsSearch.groups.history",
    groupFallbackLabel: "History",
    keywords: [
      "file tts history",
      "retain converted audio",
      "regenerate",
      "export",
      "comparison",
      "storage limit",
      "история файлов tts",
      "сохранить аудио",
      "пересоздать",
      "экспорт",
    ],
  },
] as const satisfies readonly SettingsSearchEntry[];
